# Generated by Django 4.2.7 on 2025-11-02 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique password reset token', unique=True, verbose_name='reset token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time', verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has been used', verbose_name='is used')),
                ('user', models.ForeignKey(help_text='User associated with this reset token', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='authenticat_token_3288c7_idx'), models.Index(fields=['user', 'is_used'], name='authenticat_user_id_9751b1_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_8662be_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique verification token', unique=True, verbose_name='verification token')),
                ('email', models.EmailField(help_text='Email address to be verified', max_length=254, verbose_name='email to verify')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time', verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has been used', verbose_name='is used')),
                ('user', models.ForeignKey(help_text='User associated with this verification token', on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='authenticat_token_e79b2f_idx'), models.Index(fields=['user', 'is_used'], name='authenticat_user_id_456fdd_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_ae4371_idx')],
            },
        ),
    ]
