apiVersion: v1
kind: ConfigMap
metadata:
  name: koroh-config
  namespace: koroh-platform
data:
  # Database configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "koroh_platform"
  
  # Redis configuration
  REDIS_URL: "redis://redis-service:6379/0"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  
  # MeiliSearch configuration
  MEILISEARCH_URL: "http://meilisearch-service:7700"
  
  # Django configuration
  DJANGO_SETTINGS_MODULE: "koroh_platform.settings.production"
  DEBUG: "False"
  
  # Frontend configuration
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.koroh.dev/api/v1"
  NEXT_PUBLIC_WS_URL: "wss://api.koroh.dev/ws"
  
  # AWS configuration
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BEDROCK_REGION: "us-east-1"
  AWS_BEDROCK_DEFAULT_MODEL: "anthropic.claude-3-sonnet-20240229-v1:0"
  AWS_BEDROCK_TIMEOUT: "30"
  AWS_BEDROCK_MAX_RETRIES: "3"
  
  # Monitoring configuration
  PROMETHEUS_MULTIPROC_DIR: "/tmp/prometheus_multiproc_dir"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: koroh-secrets
  namespace: koroh-platform
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "koroh_user"
  POSTGRES_PASSWORD: "secure_password_change_in_production"
  
  # Django secret key
  DJANGO_SECRET_KEY: "django-insecure-change-in-production-with-strong-key"
  
  # AWS credentials
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  
  # MeiliSearch master key
  MEILISEARCH_MASTER_KEY: "secure-meilisearch-key"
  
  # Grafana admin password
  GRAFANA_ADMIN_PASSWORD: "secure-grafana-password"
  
  # JWT signing key
  JWT_SECRET_KEY: "jwt-secret-key-change-in-production"