# Generated by Django 4.2.7 on 2025-11-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_chatsession_is_anonymous_chatsession_session_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcontext',
            options={'verbose_name': 'Chat Context', 'verbose_name_plural': 'Chat Contexts'},
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='context_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='context_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='conversation_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='conversation_stage',
            field=models.CharField(blank=True, default='initial', max_length=50),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='conversation_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='follow_up_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='key_insights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='last_context_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='mentioned_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='previous_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='user_intent_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='user_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
